[WiP] Students
InclusiveClassrooms/skills-wheel pull request #65
Opened 2017-03-03 18:16 UTC by jackcarlisle

# not ready for review

- [ ] adds the functionality for a teacher to create students within a group 

#27

2017-03-04 17:08 UTC, samhstn requested changes
Amazing progress, glad to finally be over that many to many relationship, plain sailing from now I guess? 👍 

Let me know your thoughts on the couple of points raised, then it's good to go.

Also I feel that perhaps we could look to employ [this](https://github.com/dwyl/learn-phoenix-framework/pull/42/files#diff-43818413585772311e7de1350bfc0542R14) pattern in places in the tests

2017-03-04 17:08 UTC, samhstn commented on test/controllers/student_controller_test.exs
> +  alias Skillswheel.UserGroup
`alias Skillswheel.{ConnCase, Group, Student, User, UserGroup}` ?

Let me know if your keen to use this pattern, I like it but I'm fine with not implementing if your not a fan

2017-03-04 17:08 UTC, samhstn commented on test/controllers/student_controller_test.exs
> +
I'm finding these inserts a little long to read, could we extract out what is being done into a helper function in `test/support/test_helpers.ex`

2017-03-05 09:44 UTC, jackcarlisle commented on test/controllers/student_controller_test.exs
> +  alias Skillswheel.UserGroup
Sounds good I'll swap that over!

2017-03-05 09:45 UTC, jackcarlisle commented on test/controllers/student_controller_test.exs
> +
Yeah sounds good, I'll look into this tomorrow

2017-03-06 10:15 UTC, merged